import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const origin='https://umametry-verified-20260904.hanksleedee.chatgpt.site';
const paths=['/','/m/','/records','/review','/calibration','/analysis','/explanations','/learn','/pro-tools','/onboarding','/account','/sync','/data-transfer','/privacy-controls','/wellbeing','/install','/help','/support','/status','/trust','/terms','/privacy','/accessibility','/compatibility','/commercial-readiness','/monetization','/offer','/entitlements','/operations','/data-policy','/ads-readiness','/dashboard','/manifest.json','/robots.txt','/sitemap.xml','/ads.txt','/umametry-public-qr.png'];
const clean=s=>s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
const report={observedAt:new Date().toISOString(),origin,evidenceKind:'HTTP_RENDERED_HTML_NOT_INTERACTIVE_BROWSER',routes:[]};
let index=0;
await Promise.all(Array.from({length:4},async()=>{while(index<paths.length){const route=paths[index++];try{const started=Date.now();const response=await fetch(origin+route,{signal:AbortSignal.timeout(20000)});const type=response.headers.get('content-type')||'';const html=/text|json|xml/.test(type)?await response.text():'';const buttons=[...html.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/gi)].map(m=>({label:clean(m[2]),disabled:/\bdisabled(?:\s|=|$)/.test(m[1])}));const anchors=[...html.matchAll(/<a\b[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/gi)].map(m=>({href:m[1].replace(/&amp;/g,'&'),label:clean(m[2])}));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);report.routes.push({route,status:response.status,elapsedMs:Date.now()-started,contentType:type,title:html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'',h1:[...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>clean(m[1])),buttons,anchors,ids,fields:[...html.matchAll(/<(input|select|textarea)\b([^>]*)>/gi)].map(m=>({tag:m[1],name:m[2].match(/name="([^"]*)"/)?.[1]||'',type:m[2].match(/type="([^"]*)"/)?.[1]||'',disabled:/\bdisabled(?:\s|=|$)/.test(m[2])})),publicText:clean(html).slice(0,14000),newHomeCandidate:html.includes('home-command'),oldHero:html.includes('class="hero"')});console.log(route+' '+response.status+' controls='+buttons.length);}catch(error){report.routes.push({route,error:error.name+': '+error.message});console.log(route+' ERROR');}}}));
report.routes.sort((a,b)=>paths.indexOf(a.route)-paths.indexOf(b.route));
report.sameOriginFragments=[];
for(const source of report.routes)for(const a of source.anchors||[]){const u=new URL(a.href,origin+source.route);if(u.origin!==origin||!u.hash)continue;const target=report.routes.find(r=>r.route.replace(/\/$/,'')===u.pathname.replace(/\/$/,''));if(target)report.sameOriginFragments.push({from:source.route,label:a.label,target:u.pathname+u.hash,targetExistsInServerHTML:target.ids?.includes(u.hash.slice(1))??false});}
await writeFile(new URL('public-http-inventory.json',import.meta.url),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({routes:report.routes.length,statuses:report.routes.reduce((a,r)=>(a[r.status||'error']=(a[r.status||'error']||0)+1,a),{}),missingFragments:report.sameOriginFragments.filter(x=>!x.targetExistsInServerHTML)}));
